linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  paralleltest:
    ignore-missing: true
issues:
  exclude-use-default: false
output:
  sort-results: true
